name: CI

on: 
  push:
    branches:
      - yg/github-actions

jobs:
  build-nodejs:
    name: Build Node.js ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [windows, ubuntu, macOS]
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install --ignore-scripts
        npm test node
      env:
        CI: true
