name: Publish Package Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release version tag
        required: true
        type: string
        default: 'latest'
      commit:
        description: Optional commit to publish from
        required: false
        type: string
      package:
        description: 'Package'
        required: true
        default: 'realm'
        type: choice
        options:
        - '@realm/babel-plugin'
        - '@realm/common'
        - '@realm/network-transport'
        - '@realm/react'
        - '@realm/tools'
        - '@realm/web'

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publishing release for ${{inputs.package}}"
