name: Publish Realm Web

on:
  push:
    tags:
      - realm-web-v*
env:
  REALM_DISABLE_ANALYTICS: 1

jobs:
  test-build-and-publish:
    name: Test, build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install npm v7
        run: npm install -g npm@8
      # Install the root package (--ignore-scripts to avoid downloading or building the native module)
      - run: npm ci --ignore-scripts
      # Bootstrap lerna sub-packages
      - run: npx lerna bootstrap --scope realm-web --include-dependencies --include-dependents
      - run: npm run build
        working-directory: packages/realm-web
      - run: npm test
        working-directory: packages/realm-web
      # Login with the Docker CLI to enable the integration test harness to pull the mongodb-realm-test-server
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: realm-ci
          password: ${{ secrets.REALM_CI_GITHUB_API_KEY }}
      - name: Run integration tests
        run: npm run test:github
        working-directory: packages/realm-web-integration-tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BAAS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BAAS_AWS_SECRET_ACCESS_KEY }}
          MONGODB_REALM_TEST_SERVER: "2022-06-15"
      # Publish the package
      - run: npm publish
        working-directory: packages/realm-web
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
